# Generated by Django 4.2.2 on 2023-06-08 13:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('address', models.TextField(verbose_name='آدرس اتاق')),
                ('seats_count', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MeetingManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_manager', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(null=True, verbose_name='زمان شروع جلسه')),
                ('end_time', models.DateTimeField(null=True, verbose_name='زمان اتمام جلسه')),
                ('duration', models.IntegerField(null=True)),
                ('meeting_manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Meeting.meetingmanager')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Meeting.room')),
            ],
        ),
    ]
